export const allowedPivotTables = {
  jobs: [
    "tb_jobs_cities",
    "tb_jobs_countries",
    "tb_jobs_educations",
    "tb_jobs_experiences",
    "tb_jobs_genders",
    "tb_jobs_marital_statuses",
    "tb_jobs_modes",
    "tb_jobs_positions",
    "tb_jobs_program_studies",
    "tb_jobs_provinces",
    "tb_jobs_religions",
  ],
  internships: [
    "tb_internships_cities",
    "tb_internships_countries",
    "tb_internships_educations",
    "tb_internships_genders",
    "tb_internships_modes",
    "tb_internships_positions",
    "tb_internships_program_studies",
    "tb_internships_provinces",
    "tb_internships_religions",
    "tb_internships_semesters",
  ],
  trainings: [
    "tb_trainings_cities",
    "tb_trainings_countries",
    "tb_trainings_educations",
    "tb_trainings_modes",
    "tb_trainings_program_studies",
    "tb_trainings_provinces",
    "tb_trainings_semesters",
    "tb_trainings_skills",
    "tb_trainings_training_types",
  ],
  expos: ["tb_expos_cities", "tb_expos_companies", "tb_expos_countries", "tb_expos_educations", "tb_expos_expo_types", "tb_expos_modes", "tb_expos_positions", "tb_expos_program_studies", "tb_expos_provinces"],
  companies: ["tb_companies_industries"],
};
